### ISSUE TITLE
Issue with using aspose word with celery worker

### ISSUE THREAD

**Issue by MugdhaHardikar-GSLab** [aspose-words/Aspose.Words-for-Python-via-.NET#36]
I am trying to use the aspose.word inside celery worker. When i try to load a **".doc"** file using the below API my worker gets killed:

doc = aw.Document(file_path)

**Stacktrace:**
async_framework-celery-worker-1  | [2023-06-15 07:34:52,105: ERROR/ForkPoolWorker-2] Chord 'caeb5bc7-7b4c-4542-a032-dc66e7721a87' raised: WorkerLostError('Worker exited prematurely: signal 6 (SIGABRT) Job: 3.')
async_framework-celery-worker-1  | Traceback (most recent call last):
async_framework-celery-worker-1  |   File "/usr/local/lib/python3.10/site-packages/celery/app/builtins.py", line 78, in unlock_chord
async_framework-celery-worker-1  |     ret = j(
async_framework-celery-worker-1  |   File "/usr/local/lib/python3.10/site-packages/celery/result.py", line 746, in join
async_framework-celery-worker-1  |     value = result.get(
async_framework-celery-worker-1  |   File "/usr/local/lib/python3.10/site-packages/celery/result.py", line 219, in get
async_framework-celery-worker-1  |     self.maybe_throw(callback=callback)
async_framework-celery-worker-1  |   File "/usr/local/lib/python3.10/site-packages/celery/result.py", line 335, in maybe_throw
async_framework-celery-worker-1  |     self.throw(value, self._to_remote_traceback(tb))
async_framework-celery-worker-1  |   File "/usr/local/lib/python3.10/site-packages/celery/result.py", line 328, in throw
async_framework-celery-worker-1  |     self.on_ready.throw(*args, **kwargs)
async_framework-celery-worker-1  |   File "/usr/local/lib/python3.10/site-packages/vine/promises.py", line 234, in throw
async_framework-celery-worker-1  |     reraise(type(exc), exc, tb)
async_framework-celery-worker-1  |   File "/usr/local/lib/python3.10/site-packages/vine/utils.py", line 30, in reraise
async_framework-celery-worker-1  |     raise value
async_framework-celery-worker-1  | billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 6 (SIGABRT) Job: 3.

**Versions:**
celery = "5.1.2" 
aspose-words = "^23.4.0"

If I start the worker with "celery worker --pool solo" option then aspose loads fine but I need to process a lot of data and could not go with solo option.

I have already checked that I have sufficient resources and the doc file i am trying is very small with "4-5 lines" only.

Any help/ pointers would be really appreciated.

**Comment by AlexNosk** [comment]
@MugdhaHardikar-GSLab I have logged the problem in our defect data base as **WORDSNET-25547**. We will investigate the issue and provide you more information.

PS: The main place or getting support is Aspose.Words support forum. So please post your questions in the forum to get timely response:
https://forum.aspose.com/c/words/8

**Comment by KotovDE** [comment]
@MugdhaHardikar-GSLab 
Please provide a python script example, where exception occurs and describe step by step how you run this script.
Thanks

**Comment by taoztw** [comment]
I would like to ask if there is any latest progress?🚀

**Comment by AlexNosk** [comment]
@taoztw Unfortunately, there is no update regarding the issue. Could you please provide a python script example, where exception occurs and describe step by step how you run this script.

**Comment by huangwuying** [comment]
请问目前有进展吗

**Comment by MugdhaHardikar-GSLab** [comment]
I will update the script where i found the issue in couple of days.
Thanks,
Mugdha

**Comment by akash-s-simformsolutions** [comment]
any updates on solution ?

**Comment by AlexNosk** [comment]
@akash-s-simformsolutions Unfortunately, there are no updates regarding the issue.

**Comment by kkkseil** [comment]
Try running with solo pool
